telemetry migration
ploomber/sklearn-evaluation pull request #120
Opened 2022-12-23 21:58 UTC by edublancas

closes https://github.com/ploomber/sklearn-evaluation/issues/105

I migrated the telemetry to use the new module in ploomber-core. this gives us more flexibility to log certain input parameters. furthermore, we can now share this logic in other projects.

cc @idomic

2022-12-24 14:23 UTC, idomic commented on src/sklearn_evaluation/evaluator.py
> +    @tel_clf_eval.log_call()
Why aren't we passing here feature/action?

2022-12-24 14:24 UTC, idomic commented on src/sklearn_evaluation/plot/classification.py
> +    @tel_cm.log_call(log_args=True, ignore_args={"y_true", "y_pred", "cm"})
I hope these are stored in the metadata object, else it'll make it hard to join both event types

2022-12-24 14:25 UTC, idomic commented on src/sklearn_evaluation/plot/classification.py
> +    @tel_cm.log_call()
Same as above, missing action, we want to know what was used.

2022-12-24 14:26 UTC, idomic commented on src/sklearn_evaluation/plot/classification.py
> +@tel_cm.log_call(action="function")
I see here the action is function, super generic, how would we know it was a confusion matrix?

2022-12-24 14:28 UTC, idomic commented on src/sklearn_evaluation/plot/feature_ranking.py
> +from sklearn_evaluation.telemetry import telemetry
We probably want the module to be called _telemetry?

2022-12-24 14:29 UTC, idomic commented on src/sklearn_evaluation/plot/metrics.py
> +from sklearn_evaluation.telemetry import telemetry
same, `sklearn_evaluation._telemetry`

2022-12-24 14:31 UTC, idomic commented on src/sklearn_evaluation/tracker.py
> +tel_tracker = telemetry.create_group("sqlitetracker")
Again, we're changing SQLiteTracker to sqlitetracker, we might see a big hit on the data unless we change it in both ends.

2022-12-24 14:34 UTC, idomic requested changes
Added a few comments, we need to keep the same convention or change the dashboard to accept these new events/data.
Something that would make this review way easier is keeping `'` vs changing to `"` and some other styling/whitespaces that was added (I assume it's automatic and not sure why git shows it). i.e instead of 22 changed files it'd be maybe 5 and I'm sure it's all on the dev IDE.

2022-12-24 14:35 UTC, idomic commented on src/sklearn_evaluation/plot/classification.py
> +@tel_cm.log_call(action="function")
I assume by the group? But still why call it function vs it's name

2023-01-12 19:28 UTC, idomic commented
@edublancas any updates on this? let's try closing it.

2023-01-23 18:45 UTC, edublancas commented
it's gonna be difficult to merge this since there's been so many changes, and there is little benefit to it. closing it

2023-01-23 18:45 UTC, closed without merging