Added classification quickstart
ploomber/sklearn-evaluation pull request #140
Opened 2022-12-27 15:22 UTC by idomic

Partial solution to the quick start guides, focusing on classification.

2022-12-27 16:35 UTC, edublancas requested changes

2022-12-27 16:35 UTC, edublancas commented on docs/quickstart/classification.md
> +In this guid we'll show how to compare and evaluate models with sklearn-evaluation.
pass this through a spell check since there are a few typos. I saw "guid", and "paraters"

2022-12-27 16:35 UTC, edublancas commented on docs/quickstart/classification.md
> +In step 4 & 5 the real value of SKE comes into fruition as we get a lot of visualizations out of the box which will help us compare and evaluate the models, making it easier to pick the optimal one.
> SKE

let's not use abbreviations since people are not familiar with them

2022-12-27 16:56 UTC, edublancas approved these changes

2022-12-27 16:57 UTC, merged

2022-12-27 16:58 UTC, edublancas commented
please wait for a few mins til the docs build again and ensure the quickstart looks good

2022-12-27 19:39 UTC, neelasha23 commented
As per this [roadmap](https://github.com/ploomber/sklearn-evaluation/issues/107) we should have section wise quickstarts. Currently there is one general quickstart in the [docs](https://sklearn-evaluation.ploomber.io/en/latest/quickstart/classification.html) with classifiers. It's going to get longer if we keep adding other sections like regression, clustering, etc.
Thoughts? @idomic @edublancas

2022-12-27 20:29 UTC, idomic commented
Yeah I did it on it's own on purpose, that way you can concentrate all of the quickstart guides in one location.
It's also always on top vs scrolling to the section let's say clustering, and then hitting the quick start.

2022-12-27 22:50 UTC, edublancas commented
I think it should be separate files so they appear as different sections and users can click on whatever section is relevant to them, rather than clicking on quickstart and then scrolling

2022-12-28 00:53 UTC, idomic commented
Yeah of course, just like we talked offline, else it will be confusing if all is meshed.