Support different inputs for ROC
ploomber/sklearn-evaluation pull request #221
Opened 2023-01-17 20:06 UTC by yafimvo

## Describe your changes
Added support for 3 different inputs for ROC curve: lables/classes array, onehot encoded array, and array of values.

```
array([0, 1, 2])

array([[0, 1, 0], 
        [1, 0, 0], 
        [0, 0, 1]])

array([[0.1, 0.8, 0.1], 
        [0.8, 0.1, 0.1], 
        [0.1, 0.1, 0.8]])
```

## Issue ticket number and link
Closes #98  

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have added thorough tests (when necessary).
- [X] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2023-01-17 20:21 UTC, yafimvo commented
@edublancas  @idomic 
I added an example to [classifications](https://sklearn-evaluation--221.org.readthedocs.build/en/221/quickstart/classification.html#evaluate-our-model). 

I think it's not the best example for ROC since the accuracy is almost 100% and the curves are "too good"

![image](https://user-images.githubusercontent.com/103026689/213004329-b38fa94e-a756-46c4-9543-7fb31420ecb3.png)

2023-01-27 21:01 UTC, idomic approved these changes
Looking good, just rebase on main and let's merge this.

2023-01-27 21:16 UTC, edublancas requested changes

2023-01-27 21:16 UTC, edublancas commented on docs/quickstart/classification.md
> +```
let's move this to the docstring. and clarify that the first two formats are for the y_true argument and the second format is for y_score

2023-01-27 21:16 UTC, edublancas commented on docs/quickstart/classification.md
> +plot.roc(y_test, y_pred_dt)
there's an error here, y_pred_dt is created with `y_pred_dt = dt_model.predict(X_test)`

but it should be `y_pred_dt = dt_model.predict_proba(X_test)`

note that some plots like confusion matrix need the output of `predict`, and others like roc need `predict_proba`

2023-01-27 21:16 UTC, edublancas commented
found a minor issue

2023-01-29 08:21 UTC, yafimvo commented
@edublancas @idomic 
This PR should be closed since we[ took another approach](https://github.com/ploomber/sklearn-evaluation/issues/98#issuecomment-1387078829) where ROC inputs should be "scores" like for `y_score` and "classes"/"one hot" for `y_test`.

2023-01-29 14:45 UTC, closed without merging