adds description for examples
ploomber/sklearn-evaluation pull request #258
Opened 2023-01-30 17:26 UTC by ShubhamGawande191

## Describe your changes
Added descriptions for examples, also added a few generic comments in examples, and commented out a few useless things which don't contribute to the actual example. 

## Issue ticket number and link
Closes #217 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-01-30 17:37 UTC, ShubhamGawande191 commented
examples from which I commented out code:
precision_recall_multiclass.py
precision_recall.py
rco_binary_classification.py
roc_comparison.py
roc_new_api.py
roc.py
confusion_matrix.py [haven't commented out yet]

Also, in the src/sklearn_evaluation/plot/roc.py, for the ROCAdd example, I didn't find any roc_add.py. I am guessing it is the same as roc_comparison.py. If it is something different, let me know what do I add there.

2023-01-31 18:50 UTC, edublancas commented
> Also, in the src/sklearn_evaluation/plot/roc.py, for the ROCAdd example, I didn't find any roc_add.py. I am guessing it is the same as roc_comparison.py. 

yep. ROCAdd is the same as roc_compaison, so no need to add more examples.

2023-01-31 18:53 UTC, edublancas requested changes
looks great! just minor formatting changes

2023-01-31 18:53 UTC, edublancas commented on src/sklearn_evaluation/plot/classification.py
> +    This example illustrates how to plot a confusion matrix for binary classifier
please make descriptions shorter, add a colon at the end, and check any missing prepositions

example. from:

```
This example illustrates how to plot a confusion matrix for binary classifier
```

to:

```
Plot a confusion matrix for a binary classifier:
```


apply the same for the other descriptions

2023-02-03 05:18 UTC, closed without merging

2023-02-03 12:43 UTC, edublancas commented
any updates? are you opening another pull request?

2023-02-03 13:18 UTC, ShubhamGawande191 commented
Yes, just now opened a pull request