Overfitting/Underfitting tutorial
ploomber/sklearn-evaluation pull request #299
Opened 2023-02-23 22:51 UTC by gtduncan

## Describe your changes
Tutorial on underfitting/overfitting implementing learning curves created by sk-eval

## Issue ticket number and link
Closes #197 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

2023-02-27 23:18 UTC, edublancas requested changes
looks great, added minor observations

2023-02-27 23:18 UTC, edublancas commented on docs/_toc.yml
> +    - file: tutorials/underfitting_overfitting
let's put this under the optimization section

2023-02-27 23:18 UTC, edublancas commented on docs/tutorials/underfitting_overfitting.md
> +X, y = data[0], data[1]
cleaner version

```suggestion
X, y = make_classification(
    n_samples=1000, random_state=0, class_sep=0.2
)
```

2023-02-27 23:18 UTC, edublancas commented on docs/tutorials/underfitting_overfitting.md
> +X, y = data[0], data[1]
```suggestion
X, y = make_classification(
    n_samples=100, n_features=20, n_informative=2,
    n_repeated=2, n_redundant=2, class_sep=0, random_state=0
)
```

2023-02-27 23:18 UTC, edublancas commented on docs/tutorials/underfitting_overfitting.md
> +cross-validation, ensemble methods
```suggestion
Some other methods include: cross-validation, and ensemble methods.
```

2023-02-27 23:18 UTC, edublancas commented on docs/tutorials/underfitting_overfitting.md
> +ensemble methods, [hyperparameter tuning](https://guides.lib.purdue.edu/d-velop/ml-dl/automl1), transfer learning
```suggestion
Some other methods include: ensemble methods, [hyperparameter tuning](https://guides.lib.purdue.edu/d-velop/ml-dl/automl1), and transfer learning.
```

2023-02-28 16:03 UTC, gtduncan commented
Just made those changes!

2023-02-28 19:50 UTC, idomic commented
@gtduncan please resolve the `CHANGELOG.md` conflicts so we can merge.

2023-03-02 13:26 UTC, edublancas approved these changes

2023-03-02 13:26 UTC, merged