Target analysis
ploomber/sklearn-evaluation pull request #77
Opened 2022-11-18 16:31 UTC by neelasha23

2022-11-27 12:14 UTC, yafimvo requested changes
Tested it locally and it looks good! One note, I think we should track `def target_plot` usage.

2022-11-27 12:14 UTC, yafimvo commented on src/sklearn_evaluation/plot/target_analysis.py
> +def target_plot(y_train, y_test=None, labels=None, colors=None, ax=None):
We need to track the usage of this method. We can do it with `@SKLearnEvaluationLogger.log(feature='plot')`

2022-11-27 15:03 UTC, yafimvo commented
looking good to me
@idomic @neelasha23

2022-11-28 17:40 UTC, idomic commented
@neelasha23 looking good, the only thing that's missing is documentation, did you add it besides the sample notebook? We need to add some details about this plot, when to use it, what parameters it takes, common pitfalls etc. into the right section (let's say metrics)

2022-11-28 17:48 UTC, neelasha23 commented
When to use and parameters are mentioned in the guide. I will look into common pitfalls if any
@idomic

2022-11-30 15:06 UTC, edublancas commented
@neelasha23 for some reason, github did not trigger the CI. can you try adding a new commit and push?

```
git commit --allow-empty -m 'trigger ci'
```

2022-11-30 15:58 UTC, neelasha23 commented
Done @edublancas

2022-11-30 17:00 UTC, edublancas approved these changes

2022-11-30 17:00 UTC, merged

2022-11-30 17:01 UTC, edublancas commented
nice work! 🚀